# **NumPy**

In [1]:
import numpy as np

### Cree un vector dentro del rango (10, 49)

In [3]:
mat = np.arange(10, 50)
mat

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

### Invierte el resultado de todo el vector, es decir de (49, 10)

In [5]:
mat[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

### El arreglo anterior conviertelo a una matriz de (8, 5)

In [9]:
mat.reshape(8, 5)

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

### Crea una matriz 3x3 con valores de 0 a 8

In [12]:
mat = np.arange(0, 9).reshape(3, 3)
mat

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### Crea una matriz identidad de 6x6

In [20]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

### Crea una matriz de 5x5 con valores random

In [24]:
mat = np.random.rand(3, 3, 3)
mat

array([[[0.11627905, 0.65111522, 0.6376302 ],
        [0.59847104, 0.94838123, 0.84707096],
        [0.03981754, 0.9121492 , 0.09448865]],

       [[0.29782487, 0.00968967, 0.12401377],
        [0.20191057, 0.20945   , 0.78123135],
        [0.9810079 , 0.75802234, 0.0659422 ]],

       [[0.23456095, 0.95367245, 0.12967523],
        [0.57344019, 0.04067357, 0.72804602],
        [0.1748975 , 0.59832778, 0.46848955]]])


### Crear una matriz de 10x10 con 1's en los bordes y 0 en el interior (con rangos de indices)¶

### Crear una matriz de 5x5 con valores en los renglones que vayan de 0 a 4¶


### Crear dos arreglos al azar A y B, verificar si son iguales¶

### Crear una matriz de 5x5 en la que su diagonal principal cuente con valores arbitrarios, mientras que los demas valores deben ser 0.

### Genera un vector de longitud (8), con valores random o determina valores

### Del arreglo anterior comprobar si algun valor es 0 e imrpimir True o False según sea el caso.

### Genera un vector con valores reales y complejos, ejemplo:  	``` np.array([1, 2, -1+3j, 3, 2j])

### Del vector genarado anteriormente comrpobar cuales valores son complejos.