##### Numpy

In [1]:
import numpy as np

<img src="https://quppler.com/wp-content/uploads/2019/03/python-numpy-array.png">

In [2]:
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(type(array))

<class 'numpy.ndarray'>


In [4]:
print(array.shape)

(3, 3)


In [5]:
print(array[0])
print(array[1])
array[2] = 5
print(array[2])

[1 2 3]
[4 5 6]
[5 5 5]


In [6]:
print("Acceder al valor de la matriz", array[2, 0]) #[fila, columna]

Acceder al valor de la matriz 5


$ I^{n \times n} =
\left( \begin{array}{cccc}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9 \\
\end{array} \right) $

In [7]:
#Un array lleno de ceros
zeros = np.zeros([7, 7])
print(zeros)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [8]:
#Crear un array lleno de un valor determinado
eights = np.full([4, 4], 8)
print(eights)

[[8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]]


In [9]:
#Llenar la diagonal principal con '1'
eye = np.eye(9 , 9)
print(eye)

[[1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [10]:
#Matriz con puros '1'
ones = np.ones((3, 7, 3))
print(ones)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


<img src="https://miro.medium.com/max/1440/1*Ikn1J6siiiCSk4ivYUhdgw.png" height="700" width="700">

In [11]:
## Arreglo de 4x4 de numeros random
random = np.random.random((4, 4))
print(random)

[[0.76694805 0.97163412 0.36513764 0.31921393]
 [0.60879539 0.6787363  0.46700605 0.39159828]
 [0.68386927 0.43592623 0.75142285 0.10168551]
 [0.38887596 0.25656208 0.56225261 0.09913526]]


##### Array de indices

In [12]:
array = np.array([[10, 9, 8], [11, 12, 13], [14, 15, 20], [21, 24, 30]])
print(array)
print(array.shape)

[[10  9  8]
 [11 12 13]
 [14 15 20]
 [21 24 30]]
(4, 3)


In [13]:
#Creamos dos arrays con numeros enteros que utilizaremos como indices
cols = np.array([0, 1, 2, 0])
rows = np.arange(4)

print("Valores de columnas -> ", cols)
print("Valores de filas -> ", rows)

Valores de columnas ->  [0 1 2 0]
Valores de filas ->  [0 1 2 3]


In [14]:
for row, col in zip(rows, cols):
    print('(', row, ',', col, ')')

( 0 , 0 )
( 1 , 1 )
( 2 , 2 )
( 3 , 0 )


In [15]:
print("Valores impresos con los arrays que queremos -> ", array[rows, cols])

Valores impresos con los arrays que queremos ->  [10 12 20 21]


In [16]:
print(array)
array[rows, cols] += 100
array

[[10  9  8]
 [11 12 13]
 [14 15 20]
 [21 24 30]]


array([[110,   9,   8],
       [ 11, 112,  13],
       [ 14,  15, 120],
       [121,  24,  30]])

In [17]:
#Crear un filtro
filter_array = (array > 15)
filter_array

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True],
       [ True,  True,  True]])

In [18]:
#Imprimimos los valores que cumplen la condicion del filtro
new_array_filter = array[filter_array]
new_array_filter

array([110, 112, 120, 121,  24,  30])

##### Slice en Array

In [19]:
new_array = np.array([[2, 3, 5, 6, 7, 0], [23, 45, 6, 7, 90, 56], [12, 14, 67, 80, 24, 28], [34, 45, 89, 35, 78, 86]])
new_array

array([[ 2,  3,  5,  6,  7,  0],
       [23, 45,  6,  7, 90, 56],
       [12, 14, 67, 80, 24, 28],
       [34, 45, 89, 35, 78, 86]])

In [20]:
slice = new_array[:2, 1:3]
slice

array([[ 3,  5],
       [45,  6]])

In [21]:
slice[0, 0] += 100
slice

array([[103,   5],
       [ 45,   6]])

In [22]:
#Al sumar 100 a la posicion (0,0) del slice realmente lo sumamos al original, un slice es un apuntador
new_array

array([[  2, 103,   5,   6,   7,   0],
       [ 23,  45,   6,   7,  90,  56],
       [ 12,  14,  67,  80,  24,  28],
       [ 34,  45,  89,  35,  78,  86]])

In [23]:
#Para crear un array nuevo a partir del slice que hicimos
array_slice = np.array(slice)
array_slice

array([[103,   5],
       [ 45,   6]])

In [24]:
a = np.array([[2, 4, 5, 6], [8, 9, 0, 6]])
b = np.array([[4, 5, 6, 8], [23, 12, 6, 7]])

In [25]:
#Operaciones entre arrays
#Resta
print(np.subtract(b,a))

[[ 2  1  1  2]
 [15  3  6  1]]


In [26]:
#Suma
print(np.add(b,a))

[[ 6  9 11 14]
 [31 21  6 13]]


In [27]:
#Multiplicacion
print(np.multiply(a,b))

[[  8  20  30  48]
 [184 108   0  42]]


In [28]:
#Division
print(np.divide(a,b))

[[0.5        0.8        0.83333333 0.75      ]
 [0.34782609 0.75       0.         0.85714286]]


#### Operaciones Estadisticas basicas

In [29]:
array_random = np.random.rand(2, 5)
array_random

array([[0.29670357, 0.27357713, 0.93326577, 0.61114902, 0.07880201],
       [0.12456377, 0.8888479 , 0.5339089 , 0.14564777, 0.35471113]])

In [30]:
#Calcula la media(promedio) de un array
print(array_random.mean())

0.4241176960834843


In [31]:
#Sacar el promedio fila por fila
#eje 0 = columnas
#eje 1 = filas
print(array_random.mean(axis = 1))

[0.4386995  0.40953589]


In [32]:
#Sacamos el promedio columna por columna
print(array_random.mean(axis = 0))

[0.21063367 0.58121251 0.73358733 0.37839839 0.21675657]


In [33]:
#Creamos un array de 10 elementos aleatorios
array_disorder = np.random.rand(2, 3)
array_disorder

array([[0.07260767, 0.98951338, 0.75201697],
       [0.06221866, 0.1722389 , 0.24232813]])

In [34]:
#Creamos una copia
order = np.array(array_disorder)
order

array([[0.07260767, 0.98951338, 0.75201697],
       [0.06221866, 0.1722389 , 0.24232813]])

In [35]:
#Ordenamos el arreglo
order.sort()
order

array([[0.07260767, 0.75201697, 0.98951338],
       [0.06221866, 0.1722389 , 0.24232813]])

In [36]:
#Buscando elementos unicos
uniq_array = np.array([1, 2, 3, 1, 2, 3, 1, 2, 3])
print(np.unique(uniq_array))

[1 2 3]


In [37]:
#Operaciones en conjunto
s1 = np.array(['silla', 'mesa', 'lampara'])
s2 = np.array(['silla', 'mesa', 'cajon'])

In [38]:
#Interseccion, sacamos los puntos iguales de los arrays
print(np.intersect1d(s1, s2))

['mesa' 'silla']


In [39]:
#Union en 1d, nos quedamos con elementos unicos de los dos arrays
print(np.union1d(s1, s2))

['cajon' 'lampara' 'mesa' 'silla']


In [40]:
#Elementos de s1 que no esten en s2
print(np.setdiff1d(s1, s2))

['lampara']


In [43]:
#Que elementos de s1 estan en s2
print(np.in1d(s1, s2))

[ True  True False]


### Operaciones frecuentes

In [44]:
ex1 = np.array([[2, 3], [5, 7]])
print("Dimension ---> ", ex1.shape)
print("Sumamos los elementos de un array ---> ", np.sum(ex1))

Dimension --->  (2, 2)
Sumamos los elementos de un array --->  17


In [45]:
print("Sumamos solo una columna ---> ", np.sum(ex1, axis = 0))
print("Sumamos solo una fila ---> ", np.sum(ex1, axis = 1))

Sumamos solo una columna --->  [ 7 10]
Sumamos solo una fila --->  [ 5 12]


### Reformateando un array (IMPORTANTE)

In [46]:
arr = np.arange(20)
print("Arreglo ---> ", arr)
print("Dimension ---> ", arr.shape)

Arreglo --->  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Dimension --->  (20,)


In [50]:
reshape_arr = arr.reshape(4, 5)
print(reshape_arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [51]:
#Transpuesta de un array
reshape_arr.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [52]:
#Where ..... MUY UTIL
mat = np.random.rand(4,4)
mat

array([[0.90913891, 0.90504651, 0.19230904, 0.21699448],
       [0.16316621, 0.93546352, 0.39267397, 0.94401305],
       [0.48891801, 0.43736594, 0.04748261, 0.95746455],
       [0.90402089, 0.44251761, 0.39107526, 0.48546517]])

In [53]:
#Le pasamos array de condicion, (array --condicion--, nuevo valor donde se cumpla, nuevo valor donde no se cumpla)

np.where(mat > 0.3, 1, 0)

array([[1, 1, 0, 0],
       [0, 1, 1, 1],
       [1, 1, 0, 1],
       [1, 1, 1, 1]])

In [55]:
#Comprobar si algun elemto del array es verdadero, funciona tanto con numeros como con booleanos

array_bools = np.array([0, 0, 5, 0, 0])
array_bools.any()

True

In [56]:
#Comprobar si todos los elementos del array son True

array_true = np.array([1, 1, 1, False])
array_true.all()

False

### Uniendo Data Sets

In [58]:
###Creamos un array de numeros aleatorios con el metodo --->  np.random.randint(-numero menor-, -numero mayor-, -forma-)
X = np.random.randint(low=2, high=20, size=(2, 2))

print(X)

K = np.random.randint(low=2, high=20, size=(2, 2))

print("\n", K)

[[10  6]
 [13 15]]

 [[ 5  8]
 [15  2]]


In [59]:
## Unimos 'apilando' verticalmente
np.vstack((K, X))

array([[ 5,  8],
       [15,  2],
       [10,  6],
       [13, 15]])

In [60]:
## Apilamos horizontalmente
np.hstack((K, X))

array([[ 5,  8, 10,  6],
       [15,  2, 13, 15]])

In [61]:
#Podemos unir concatenando
np.concatenate([K, X], axis = 0)

array([[ 5,  8],
       [15,  2],
       [10,  6],
       [13, 15]])

In [62]:
np.concatenate([K, X], axis = 1)

array([[ 5,  8, 10,  6],
       [15,  2, 13, 15]])

### Propagacion 